name: HACS Action
on: 
  workflow_call:
    inputs:
      ignore:
        description: "A space seperated list of ignored checks, for valid entries see README.md"
        required: false
        default: ""
        type: string
      category:
        description: "The category of repository"
        required: true
        type: string
      repository:
        description: "The full name of repository"
        required: false
        type: string
      comment:
        description: "Post a comment to the PR with the result of the checks"
        required: false
        default: true
        type: boolean

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      name: cleanup
      run: |
        bash "${GITHUB_ACTION_PATH}/helpers/cleanup"

    - shell: bash
      id: init
      run: |
        echo "::group::init"
        mkdir -p "${GITHUB_ACTION_PATH}/data"

        git clone --quiet --depth 1 https://github.com/hacs/integration.git "${GITHUB_ACTION_PATH}/hacs" > /dev/null

        if [ -n "${{ github.event.inputs.repository }}" ]; then
          repository="${{ github.event.inputs.repository }}"
        elif [ -n "${{ inputs.repository }}" ]; then
          repository="${{ inputs.repository }}"
        else
          repository="${{ github.repository }}"
        fi

        if [ -n "${{ github.event.inputs.category }}" ]; then
          category="${{ github.event.inputs.category }}"
        else
          category="${{ inputs.category }}"
        fi

        if [ "${{ github.repository }}" != "$repository" ]; then
          path="${GITHUB_ACTION_PATH}/repository"
          rm -rf "$path"
          git clone --quiet --depth 1 "https://github.com/$repository.git" "$path" > /dev/null
        else
          path="${{ github.workspace }}"
        fi

        bash "${GITHUB_ACTION_PATH}/helpers/input" repository "$repository"
        bash "${GITHUB_ACTION_PATH}/helpers/input" category "$category"

        bash "${GITHUB_ACTION_PATH}/helpers/info" "${{ github.token }}" "$repository" "${{ github.action_path }}" > /dev/null
        bash "${GITHUB_ACTION_PATH}/helpers/topics" "${{ github.token }}" "$repository" "${{ github.action_path }}" > /dev/null

        echo "::set-output name=repository::$repository"
        echo "::set-output name=category::$category"
        echo "::set-output name=path::$path"

        echo "$repository" > "${{ github.action_path }}/data/repository"
        echo "${{ github.repository }}" > "${{ github.action_path }}/data/action_repository"
        echo "$category" > "${GITHUB_ACTION_PATH}/data/category"
        echo "$path" > "${GITHUB_ACTION_PATH}/data/path"
        echo "${{ inputs.ignore }}" > "${GITHUB_ACTION_PATH}/data/ignore"
        echo "${{ github.token }}" > "${GITHUB_ACTION_PATH}/data/token"

        echo "::endgroup::"

    - shell: bash
      name: run the action
      run: |
        bash "${GITHUB_ACTION_PATH}/run"

    - shell: bash
      name: wrapup
      run: bash "${GITHUB_ACTION_PATH}/helpers/wrapup" "${GITHUB_ACTION_PATH}"

    - shell: bash
      name: cleanup
      run: |
        bash "${GITHUB_ACTION_PATH}/helpers/cleanup"
