name: Home Assistant Validation
on: [push]

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          repository: "andreas-nixdorf-de/hacs-validate/actions/hacs-validate@v2022.5.4"
      - uses: "andreas-nixdorf-de/hacs-validate/actions/hacs-validate@v2022.5.4"
        with:
          category: integration
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v2"
        - uses: "home-assistant/actions/hassfest@master"  
